import org.apache.commons.configuration2.builder.BuilderConfigurationWrapperFactory.BuilderConfigurationWrapperInvocationHandler;
public class FunctionUse2907 {
public void funcUse() {
BuilderConfigurationWrapperInvocationHandler builderconfigurationwrapperinvocationhandler = new BuilderConfigurationWrapperInvocationHandler();
builderconfigurationwrapperinvocationhandler.handleConfigurationInvocation(null,null);
}
}